[package]
name = "pezkuwi-sdk-docs-first-pezpallet"
description = "A simple pezpallet created for the pezkuwi-sdk-docs guides"
version = "0.0.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
documentation.workspace = true

[lints]
workspace = true

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
codec = { workspace = true }
docify = { workspace = true }
pezframe = { workspace = true, features = ["runtime"] }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }
scale-info = { workspace = true }

[features]
default = ["std"]
std = [
	"codec/std",
	"pezframe-support/std",
	"pezframe-system/std",
	"pezframe/std",
	"scale-info/std",
]
runtime-benchmarks = [
	"pezframe-support/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezframe/runtime-benchmarks",
]
try-runtime = [
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezframe/try-runtime",
]
serde = []
experimental = []
tuples-96 = []
