[package]
name = "pezkuwi-sdk-docs-first-runtime"
description = "A simple runtime created for the pezkuwi-sdk-docs guides"
version = "0.0.0"
license = "MIT-0"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
edition.workspace = true
publish = false
documentation.workspace = true

[lints]
workspace = true

[dependencies]
codec = { workspace = true }
scale-info = { workspace = true }
serde_json = { workspace = true }

# this is a frame-based runtime, thus importing `frame` with runtime feature enabled.
pezframe = { workspace = true, features = ["runtime"] }
pezframe-support = { workspace = true }
pezframe-system = { workspace = true }

# pallets that we want to use
pezpallet-balances = { workspace = true }
pezpallet-sudo = { workspace = true }
pezpallet-timestamp = { workspace = true }
pezpallet-transaction-payment = { workspace = true }
pezpallet-transaction-payment-rpc-runtime-api = { workspace = true }

# other pezkuwi-sdk-deps
pezframe-system-rpc-runtime-api = { workspace = true }
pezsp-api = { workspace = true }
pezsp-block-builder = { workspace = true }
pezsp-core = { workspace = true }
pezsp-genesis-builder = { workspace = true }
pezsp-keyring = { workspace = true }
pezsp-offchain = { workspace = true }
pezsp-runtime = { workspace = true }
pezsp-session = { workspace = true }
pezsp-transaction-pool = { workspace = true }

# local pezpallet templates
first-pezpallet = { workspace = true }

docify = { workspace = true }

[build-dependencies]
bizinikiwi-wasm-builder = { workspace = true, optional = true }

[features]
default = ["std"]
std = [
	"bizinikiwi-wasm-builder",
	"bizinikiwi-wasm-builder?/std",
	"codec/std",
	"first-pezpallet/std",
	"pezframe-support/std",
	"pezframe-system-rpc-runtime-api/std",
	"pezframe-system/std",
	"pezframe/std",
	"pezpallet-balances/std",
	"pezpallet-sudo/std",
	"pezpallet-timestamp/std",
	"pezpallet-transaction-payment-rpc-runtime-api/std",
	"pezpallet-transaction-payment/std",
	"pezsp-api/std",
	"pezsp-block-builder/std",
	"pezsp-core/std",
	"pezsp-genesis-builder/std",
	"pezsp-keyring/std",
	"pezsp-offchain/std",
	"pezsp-runtime/std",
	"pezsp-session/std",
	"pezsp-transaction-pool/std",
	"scale-info/std",
	"serde_json/std",
]
runtime-benchmarks = [
	"bizinikiwi-wasm-builder?/runtime-benchmarks",
	"first-pezpallet/runtime-benchmarks",
	"pezframe-support/runtime-benchmarks",
	"pezframe-system-rpc-runtime-api/runtime-benchmarks",
	"pezframe-system/runtime-benchmarks",
	"pezframe/runtime-benchmarks",
	"pezpallet-balances/runtime-benchmarks",
	"pezpallet-sudo/runtime-benchmarks",
	"pezpallet-timestamp/runtime-benchmarks",
	"pezpallet-transaction-payment-rpc-runtime-api/runtime-benchmarks",
	"pezpallet-transaction-payment/runtime-benchmarks",
	"pezsp-api/runtime-benchmarks",
	"pezsp-block-builder/runtime-benchmarks",
	"pezsp-genesis-builder/runtime-benchmarks",
	"pezsp-keyring/runtime-benchmarks",
	"pezsp-offchain/runtime-benchmarks",
	"pezsp-runtime/runtime-benchmarks",
	"pezsp-session/runtime-benchmarks",
	"pezsp-transaction-pool/runtime-benchmarks",
]
try-runtime = [
	"first-pezpallet/try-runtime",
	"pezframe-support/try-runtime",
	"pezframe-system/try-runtime",
	"pezframe/try-runtime",
	"pezpallet-balances/try-runtime",
	"pezpallet-sudo/try-runtime",
	"pezpallet-timestamp/try-runtime",
	"pezpallet-transaction-payment-rpc-runtime-api/try-runtime",
	"pezpallet-transaction-payment/try-runtime",
	"pezsp-api/try-runtime",
	"pezsp-block-builder/try-runtime",
	"pezsp-genesis-builder/try-runtime",
	"pezsp-keyring/try-runtime",
	"pezsp-offchain/try-runtime",
	"pezsp-runtime/try-runtime",
	"pezsp-session/try-runtime",
	"pezsp-transaction-pool/try-runtime",
]
serde = []
experimental = []
tuples-96 = []
